title: "Kishan Mistry"
email: kishanjaymistry@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  Newly qualified dentist from University of Central Lancashire 2018<br>Degree in Pharmacy 2010
author: "Kishan Mistry"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kjmistry.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: kishan-mistry-9b4a5334
show_excerpts: true
google_analytics: UA-134142648-1
header_pages:
  - about.md
  - treatments.md
  - currentcases.md
  - events.md
  - certificates.md
  - clinics.md
  - downloads.md
collections:
  treatments:
    output: true
  currentcases:
    output: true
  clinics:
    output: false
  certificates:
    output: false
  certificate-categories:
    output: false
  certificate-tags:
    output: false


# Build settings
markdown: kramdown
#theme: bootstrap
plugins:
  - jekyll-feed
  - jekyll-sitemap
social:
  name: Kishan Mistry
  links:
    - https://www.linkedin.com/in/kishan-mistry-9b4a5334/
lang: en_GB

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
